let client,products=[];const el=id=>document.getElementById(id),money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
function status(p){return p.quantity===0?["Sold out","out"]:p.quantity<=p.reorder_level?["Low stock","low"]:["In stock","healthy"]}
function totals(){el("total").textContent=products.length.toLocaleString("en-IN");el("units").textContent=products.reduce((sum,p)=>sum+p.quantity,0).toLocaleString("en-IN");el("low").textContent=products.filter(p=>p.quantity>0&&p.quantity<=p.reorder_level).length;el("out").textContent=products.filter(p=>p.quantity===0).length}
function render(){const q=el("inventory-search").value.toLowerCase(),filter=el("stock-filter").value;const rows=products.filter(p=>(!q||`${p.name} ${p.sku}`.toLowerCase().includes(q))&&(filter==="all"||filter===status(p)[1]));el("inventory-body").innerHTML=rows.map(p=>{const s=status(p);return `<tr><td class="product-name"><strong>${p.name}</strong><small>${p.sku}</small></td><td>${p.category}</td><td>${money.format(p.price)}</td><td><input class="qty" type="number" min="0" value="${p.quantity}" data-qty="${p.sku}" aria-label="Quantity for ${p.name}"></td><td><span class="status ${s[1]}">${s[0]}</span></td><td><button class="save" data-save="${p.sku}">Save</button></td></tr>`}).join("");document.querySelectorAll("[data-save]").forEach(button=>button.addEventListener("click",save))}
async function save(event){const sku=event.currentTarget.dataset.save,input=document.querySelector(`[data-qty="${sku}"]`),quantity=Number(input.value);if(!Number.isInteger(quantity)||quantity<0)return;event.currentTarget.disabled=true;event.currentTarget.textContent="Saving…";const {error}=await client.from("products").update({quantity}).eq("sku",sku);if(error)alert(error.message);else{products.find(p=>p.sku===sku).quantity=quantity;totals();render();el("sync-status").textContent=`Updated ${sku}`}}
async function loadProducts(){const {data,error}=await client.from("products").select("*").order("sku");if(error){el("sync-status").textContent=error.message;return}products=data;totals();render()}
async function openDashboard(){const {data:allowed,error}=await client.rpc("is_inventory_admin");if(error||!allowed){await client.auth.signOut();el("login").hidden=false;el("login-message").textContent="This account does not have inventory access.";return}el("dashboard").hidden=false;el("sign-out").hidden=false;loadProducts()}
async function start(){const cfg=window.KORIKATHA_SUPABASE;if(!cfg?.url||!cfg?.publishableKey||cfg.url.includes("YOUR_")){el("setup").hidden=false;return}client=supabase.createClient(cfg.url,cfg.publishableKey);const {data:{session}}=await client.auth.getSession();if(session)openDashboard();else el("login").hidden=false}
el("login-form").addEventListener("submit",async event=>{event.preventDefault();el("login-message").textContent="Signing in…";const {error}=await client.auth.signInWithPassword({email:el("email").value,password:el("password").value});if(error){el("login-message").textContent=error.message;return}el("login").hidden=true;openDashboard()});el("sign-out").addEventListener("click",async()=>{await client.auth.signOut();location.reload()});el("inventory-search").addEventListener("input",render);el("stock-filter").addEventListener("change",render);start();
