const state={products:[],category:new URLSearchParams(location.search).get("category")||"all",query:"",sort:"featured",visible:24};
const grid=document.querySelector("#product-grid"),count=document.querySelector("#result-count"),more=document.querySelector("#load-more");
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
function fallback(product){return product.category==="saree"?"assets/images/collection-sarees.jpg":"assets/images/collection-jewellery.jpg"}
function filtered(){const q=state.query.toLowerCase();let items=state.products.filter(p=>(state.category==="all"||p.category===state.category)&&(!q||[p.name,p.sku,p.subcategory,p.motif,p.colour].join(" ").toLowerCase().includes(q)));items.sort((a,b)=>state.sort==="price-asc"?a.price-b.price:state.sort==="price-desc"?b.price-a.price:state.sort==="name"?a.name.localeCompare(b.name):(Number(b.featured)-Number(a.featured)||a.sku.localeCompare(b.sku)));return items}
function render(){const items=filtered();count.textContent=`${items.length.toLocaleString("en-IN")} designs`;grid.innerHTML=items.slice(0,state.visible).map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" data-fallback="${fallback(p)}" alt="${p.name}" loading="lazy"><span class="badge ${p.quantity===0?"out":""}">${p.quantity===0?"Sold out":p.quantity<=p.reorder_level?"Only a few left":p.category}</span></div><div class="product-info"><div class="meta">${p.subcategory} · ${p.sku}</div><h3>${p.name}</h3><div class="price">${money.format(p.price)} <span class="compare">${money.format(p.compare_at_price)}</span></div></div></article>`).join("");grid.querySelectorAll("img").forEach(img=>img.addEventListener("error",()=>{if(img.src.endsWith(img.dataset.fallback))return;img.src=img.dataset.fallback},{once:true}));more.hidden=state.visible>=items.length}
async function load(){try{const cfg=window.KORIKATHA_SUPABASE;if(cfg?.url&&cfg?.publishableKey&&!cfg.url.includes("YOUR_")){const client=supabase.createClient(cfg.url,cfg.publishableKey);const {data,error}=await client.from("products").select("*").eq("active",true).order("sku");if(error)throw error;state.products=data}else{const response=await fetch("data/products.json");if(!response.ok)throw new Error("Catalogue unavailable");state.products=await response.json()}render()}catch(error){count.textContent="The collection could not be loaded. Please try again.";console.error(error)}}
document.querySelectorAll("[data-category]").forEach(button=>{if(button.dataset.category===state.category)document.querySelectorAll("[data-category]").forEach(b=>b.classList.toggle("active",b===button));button.addEventListener("click",()=>{state.category=button.dataset.category;state.visible=24;document.querySelectorAll("[data-category]").forEach(b=>b.classList.toggle("active",b===button));render()})});
document.querySelector("#search").addEventListener("input",e=>{state.query=e.target.value;state.visible=24;render()});document.querySelector("#sort").addEventListener("change",e=>{state.sort=e.target.value;render()});more.addEventListener("click",()=>{state.visible+=24;render()});load();
